***************
*** 3,15 ****
  MODULE_big	= amcheck
  OBJS = \
  	$(WIN32RES) \
  	verify_nbtree.o
  
  EXTENSION = amcheck
- DATA = amcheck--1.1--1.2.sql amcheck--1.0--1.1.sql amcheck--1.0.sql
  PGFILEDESC = "amcheck - function for verifying relation integrity"
  
- REGRESS = check check_btree
  
  ifdef USE_PGXS
  PG_CONFIG = pg_config
--- 3,18 ----
  MODULE_big	= amcheck
  OBJS = \
  	$(WIN32RES) \
+ 	amcheck.o \
+ 	verify_gin.o \
  	verify_nbtree.o
  
  EXTENSION = amcheck
+ DATA =  amcheck--1.1--1.2.sql amcheck--1.0--1.1.sql amcheck--1.0.sql \
+ 	amcheck--1.2--1.2.1.sql
  PGFILEDESC = "amcheck - function for verifying relation integrity"
  
+ REGRESS = check check_btree check_gin
  
  ifdef USE_PGXS
  PG_CONFIG = pg_config
