tasks:
  - init: |
      sudo apt update
      sudo apt-get install build-essential libreadline-dev zlib1g-dev flex bison libxml2-dev libxslt-dev libssl-dev libxml2-utils xsltproc ccache
    command: |
      mkdir ~/pg_local
      ./configure --prefix=$(echo ~/pg_local)
      make
      make install
