tasks:
  - init: |
      sudo apt update
      sudo apt-get install build-essential libreadline-dev zlib1g-dev flex bison libxml2-dev libxslt-dev libssl-dev libxml2-utils xsltproc ccache
    command: |
      mkdir ~/pg_local
      ./configure --prefix=$(echo ~/pg_local)
      make
      make install
      ~/pg_local/bin/initdb -D ~/pgdata
      echo "*********** Postgres installed **************"
      echo "To start it:   "
      echo "               /home/gitpod/pg_local/bin/pg_ctl -D /home/gitpod/pgdata -l logfile start"
      echo "After changes in code, rebuild&reinstall&restart:""
      echo "                make && make install"
      echo "               /home/gitpod/pg_local/bin/pg_ctl -D /home/gitpod/pgdata -l logfile restart"
